package scaffold

type Template struct {
	RelativePath string
	Content      string
}

type Option struct {
	Language  string
	Framework string
	Templates []Template
	Generator string
	Libraries []LibraryOption
}

type LibraryOption struct {
	Name string
}

var Options = []Option{
	{
		Language:  "JavaScript",
		Framework: "Vanilla",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"node src/index.js\"\n  }\n}\n",
			},
			{
				RelativePath: "src/index.js",
				Content:      "console.log(\"hello from {{.Name}}\");\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nJavaScript vanilla starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Go",
		Framework: "Vanilla",
		Libraries: []LibraryOption{
			{Name: "Gin"},
			{Name: "Gorm"},
			{Name: "Sqlc"},
		},
		Templates: []Template{
			{
				RelativePath: "main.go",
				Content:      "package main\n\nimport (\n\t\"fmt\"\n\n\t\"{{.Module}}/internal/app\"\n)\n\nfunc main() {\n\tif err := app.Run(); err != nil {\n\t\tfmt.Println(\"error:\", err)\n\t}\n}\n",
			},
			{
				RelativePath: "go.mod",
				Content:      "module {{.Module}}\n\ngo {{.GoVersion}}\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nGo vanilla starter generated by project-initiator.\n",
			},
			{
				RelativePath: "internal/app/app.go",
				Content:      "package app\n\nimport \"fmt\"\n\nfunc Run() error {\n\tfmt.Println(\"hello from {{.Name}}\")\n\treturn nil\n}\n",
			},
		},
	},
	{
		Language:  "Go",
		Framework: "Cobra",
		Libraries: []LibraryOption{
			{Name: "Gin"},
			{Name: "Gorm"},
			{Name: "Sqlc"},
		},
		Templates: []Template{
			{
				RelativePath: "go.mod",
				Content:      "module {{.Module}}\n\ngo {{.GoVersion}}\n",
			},
			{
				RelativePath: "cmd/{{.PackageName}}/main.go",
				Content:      "package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n\n\t\"github.com/spf13/cobra\"\n\t\"{{.Module}}/internal/app\"\n)\n\nfunc main() {\n\trootCmd := &cobra.Command{\n\t\tUse: \"{{.Name}}\",\n\t\tShort: \"{{.Name}} CLI\",\n\t\tRunE: func(cmd *cobra.Command, args []string) error {\n\t\t\treturn app.Run()\n\t\t},\n\t}\n\n\tif err := rootCmd.Execute(); err != nil {\n\t\t_, _ = fmt.Fprintln(os.Stderr, \"error:\", err)\n\t\tos.Exit(1)\n\t}\n}\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nGenerated by project-initiator.\n",
			},
			{
				RelativePath: "internal/app/app.go",
				Content:      "package app\n\nimport \"fmt\"\n\nfunc Run() error {\n\tfmt.Println(\"hello from {{.Name}}\")\n\treturn nil\n}\n",
			},
		},
	},
	{
		Language:  "Node.js",
		Framework: "Express",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"node src/index.js\"\n  },\n  \"dependencies\": {\n    \"express\": \"^4.19.2\"\n  }\n}\n",
			},
			{
				RelativePath: "src/index.js",
				Content:      "import express from \"express\";\n\nconst app = express();\nconst port = process.env.PORT || 3000;\n\napp.get(\"/\", (req, res) => {\n  res.send(\"Hello from {{.Name}}\");\n});\n\napp.listen(port, () => {\n  console.log(`{{.Name}} listening on ${port}`);\n});\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nGenerated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Node.js",
		Framework: "Hono",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"node src/index.js\"\n  },\n  \"dependencies\": {\n    \"hono\": \"^4.6.3\",\n    \"@hono/node-server\": \"^1.12.2\"\n  }\n}\n",
			},
			{
				RelativePath: "src/index.js",
				Content:      "import { Hono } from \"hono\";\nimport { serve } from \"@hono/node-server\";\n\nconst app = new Hono();\n\napp.get(\"/\", (c) => c.text(\"Hello from {{.Name}}\"));\n\nserve({ fetch: app.fetch, port: 3000 });\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nHono starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Node.js",
		Framework: "NestJS",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"node --loader ts-node/esm src/main.ts\"\n  },\n  \"dependencies\": {\n    \"@nestjs/common\": \"^11.0.0\",\n    \"@nestjs/core\": \"^11.0.0\",\n    \"@nestjs/platform-express\": \"^11.0.0\",\n    \"reflect-metadata\": \"^0.2.2\",\n    \"rxjs\": \"^7.8.1\"\n  },\n  \"devDependencies\": {\n    \"ts-node\": \"^10.9.2\",\n    \"typescript\": \"^5.6.3\"\n  }\n}\n",
			},
			{
				RelativePath: "tsconfig.json",
				Content:      "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \"moduleResolution\": \"Bundler\",\n    \"experimentalDecorators\": true,\n    \"emitDecoratorMetadata\": true,\n    \"strict\": true,\n    \"outDir\": \"dist\"\n  }\n}\n",
			},
			{
				RelativePath: "src/app.module.ts",
				Content:      "import { Module } from \"@nestjs/common\";\n\n@Module({})\nexport class AppModule {}\n",
			},
			{
				RelativePath: "src/main.ts",
				Content:      "import \"reflect-metadata\";\nimport { NestFactory } from \"@nestjs/core\";\nimport { AppModule } from \"./app.module.js\";\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(3000);\n  console.log(\"NestJS listening on 3000\");\n}\n\nbootstrap();\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nNestJS starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Bun",
		Framework: "Vanilla",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"bun run src/index.ts\"\n  }\n}\n",
			},
			{
				RelativePath: "src/index.ts",
				Content:      "console.log(\"hello from {{.Name}}\");\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nBun vanilla starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Bun",
		Framework: "Bun",
		Templates: []Template{
			{
				RelativePath: "package.json",
				Content:      "{\n  \"name\": \"{{.PackageName}}\",\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"bun run src/index.ts\"\n  }\n}\n",
			},
			{
				RelativePath: "src/index.ts",
				Content:      "const server = Bun.serve({\n  port: 3000,\n  fetch() {\n    return new Response(\"Hello from {{.Name}}\");\n  },\n});\n\nconsole.log(`Listening on http://localhost:${server.port}`);\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nBun starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Python",
		Framework: "Vanilla",
		Templates: []Template{
			{
				RelativePath: "app/main.py",
				Content:      "def main():\n    print(\"hello from {{.Name}}\")\n\n\nif __name__ == \"__main__\":\n    main()\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nPython vanilla starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "Python",
		Framework: "FastAPI",
		Templates: []Template{
			{
				RelativePath: "requirements.txt",
				Content:      "fastapi==0.115.5\nuvicorn==0.32.0\n",
			},
			{
				RelativePath: "app/main.py",
				Content:      "from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get(\"/\")\ndef read_root():\n    return {\"message\": \"hello from {{.Name}}\"}\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nFastAPI starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "PHP",
		Framework: "Vanilla",
		Templates: []Template{
			{
				RelativePath: "src/index.php",
				Content:      "<?php\n\necho \"hello from {{.Name}}\";\n",
			},
			{
				RelativePath: "README.md",
				Content:      "# {{.Name}}\n\nPHP vanilla starter generated by project-initiator.\n",
			},
		},
	},
	{
		Language:  "PHP",
		Framework: "Laravel",
		Generator: "composer-laravel",
		Templates: nil,
	},
}
